language: go
go: 1.10.x
go_import_path: github.com/src-d/gitbase

install:
  - make ci-install

script:
  - make ci-script

jobs:
  include:
    - {os: linux, dist: trusty, sudo: required, services: [docker]}
    - {os: osx, osx_image: xcode8.3}
    - {os: osx, osx_image: xcode9.3}
    - stage: deploy
      if: tag IS present
      os: linux
      services:
        - docker
      script:
        - make dependencies
        - make PKG_OS=linux packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
      after_deploy:
        - DOCKER_PUSH_LATEST=1 make docker-push
    - stage: deploy
      if: tag IS present
      os: osx
      osx_image: xcode9.3
      script:
        - make dependencies
        - make PKG_OS=darwin packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
