language: go

go:
  - 1.9
  - tip

go_import_path: github.com/src-d/gitquery

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  - make dependencies

script:
  - make test-coverage
  - make codecov

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
