[[constraint]]
  name = "gopkg.in/src-d/go-mysql-server.v0"
  revision = "6d0f641153f225a675d951ebf68f85558799eecd"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "github.com/src-d/go-git"
  revision = "c2ab4ac47d87f4cd674d19228e24b6696bd1db4d"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.0.0"

[[override]]
  name = "golang.org/x/sys"
  source = "github.com/golang/sys"
  revision = "f0d5e33068cb57c22a181f5df0ffda885309eb5a"

[[override]]
  name = "golang.org/x/crypto"
  source = "github.com/golang/crypto"

[[override]]
  name = "golang.org/x/text"
  source = "github.com/golang/text"

[[override]]
  name = "golang.org/x/net"
  source = "github.com/golang/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[override]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.5"

[[constraint]]
  name = "gopkg.in/bblfsh/client-go.v3"
  version = "3.0.0"

[[override]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.16.0"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v2"
  version = "2.3.0"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "^2.7.0"

[[override]]
  name = "github.com/pilosa/pilosa"
  revision = "f62dbc00b96f596a1f2ef8b4e87ba8ec847eda37"

[[override]]
  name = "github.com/pilosa/go-pilosa"
  version = "0.10.0"

[[override]]
  name = "github.com/moovweb/rubex"
  branch = "go1"

[prune]
  [[prune.project]]
    name = "gopkg.in/src-d/go-mysql-server.v0"
    go-tests = true
    non-go = true
